name: "🚀 Driverless Systems - Feature"
description: "Propose a new feature or enhancement to existing functionality"
title: "Brief description of feature"
labels: ["enhancement"]

body:
  # === WHAT ===
  - type: markdown
    attributes:
      value: |
        ## What
        Clearly describe **what** is being proposed (no justification here).

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which subsystem does this feature belong to?
      options:
        - Perception
        - Localization & Mapping
        - Planning
        - Control
        - Safety & Rule Compliance
        - Infrastructure
        - Testing
        - Hardware
        - Documentation
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What is being built
      description: Concise, concrete description of the feature
      placeholder: |
        Example:
        Implement RANSAC-based ground removal for LiDAR point clouds
    validations:
      required: true

  # === WHY ===
  - type: markdown
    attributes:
      value: |
        ## Why
        Explain **why** this feature is needed and what problem it solves.

  - type: textarea
    id: why
    attributes:
      label: Motivation
      description: Why does this matter? What problem does it solve?
      placeholder: |
        Ground points interfere with clustering and cause false positives
        in cone detection. Removing ground points earlier in the pipeline
        is expected to improve detection accuracy by 15–20%.
    validations:
      required: true

  - type: checkboxes
    id: rule_compliance
    attributes:
      label: Rule Compliance
      description: Formula Student rules consideration (check if applicable)
      options:
        - label: "Reviewed relevant FS rules for this feature"
        - label: "No rule conflicts identified"
        - label: "N/A - This feature does not interact with rule-regulated systems"

  # === SUCCESS CRITERIA ===
  - type: markdown
    attributes:
      value: |
        ## Success Criteria
        How will we know this is done and working correctly?

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Specific and measurable outcomes that must be achieved
      placeholder: |
        - [ ] Ground plane correctly identified in LiDAR point clouds
        - [ ] <5% false negatives (cones incorrectly removed)
        - [ ] Processing time <50 ms per frame on Jetson Nano
        - [ ] Works on flat terrain, inclines and bumps
        - [ ] Visualized in RViz (ground vs non-ground)
    validations:
      required: true

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Standard quality requirements
      options:
        - label: "Code reviewed and approved"
        - label: "Tests written and passing"
        - label: "Documentation updated"
        - label: "CI pipeline passing"
        - label: "Merged to main"

  # === TECHNICAL APPROACH ===
  - type: markdown
    attributes:
      value: |
        ## Technical Approach
        Optional: Proposed implementation details and design decisions.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      description: High-level approach (optional)
      placeholder: |
        1. Downsample point cloud using voxel grid
        2. Apply RANSAC plane model
        3. Classify inliers as ground
        4. Publish ground and non-ground topics

  - type: textarea
    id: risks
    attributes:
      label: Risks and Mitigation
      description: Potential issues and how to handle them (optional)
      placeholder: |
        Risk: Uneven terrain reduces accuracy
        Mitigation: Adaptive thresholding

  - type: textarea
    id: testing
    attributes:
      label: Testing Strategy
      description: How this feature will be tested (optional)
      placeholder: |
        - Synthetic point clouds
        - FSDS tracks
        - Performance benchmarks on target hardware

  # === CONTEXT & DEPENDENCIES ===
  - type: markdown
    attributes:
      value: |
        ## Context and Dependencies
        Background information and related work.

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Current state, limitations or background
      placeholder: |
        Currently using a simple height threshold for ground removal
        which fails on uneven terrain and banked corners.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Blocking or related issues (use \# to link)
      placeholder: |
        Depends on: #42 (Sensor Configuration)
        Related to: #89 (Cone Detection Pipeline)

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Links, papers, references (optional)
      placeholder: |
        - PCL RANSAC documentation
        - Ground Plane Estimation for Autonomous Racing
