blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/SDU-Vikings-Racing-Team/.github-private/blob/main/wiki-frontpage.md
    about: Check out the wiki for documentation and guides
